// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDE-iLm2FFWHoTV9xLU52in5PbepGKE6LA',
    appId: '1:1055525036473:web:78cfffefb98c182aa1d668',
    messagingSenderId: '1055525036473',
    projectId: 'lingua-ai-8be27',
    authDomain: 'lingua-ai-8be27.firebaseapp.com',
    storageBucket: 'lingua-ai-8be27.firebasestorage.app',
    measurementId: 'G-7N74623F5V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyA-bhJeHUUdlC4n6shqLrTZGR8S9d_r8',
    appId: '1:1055525036473:android:067cad3371ed6bb1a1d668',
    messagingSenderId: '1055525036473',
    projectId: 'lingua-ai-8be27',
    storageBucket: 'lingua-ai-8be27.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6fredMj0ax_bk9w71XR3KAYJiVCVwtec',
    appId: '1:1055525036473:ios:87c6805321e0c329a1d668',
    messagingSenderId: '1055525036473',
    projectId: 'lingua-ai-8be27',
    storageBucket: 'lingua-ai-8be27.firebasestorage.app',
    iosBundleId: 'com.example.linguaAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6fredMj0ax_bk9w71XR3KAYJiVCVwtec',
    appId: '1:1055525036473:ios:87c6805321e0c329a1d668',
    messagingSenderId: '1055525036473',
    projectId: 'lingua-ai-8be27',
    storageBucket: 'lingua-ai-8be27.firebasestorage.app',
    iosBundleId: 'com.example.linguaAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDE-iLm2FFWHoTV9xLU52in5PbepGKE6LA',
    appId: '1:1055525036473:web:d69c2c70aed4fdcaa1d668',
    messagingSenderId: '1055525036473',
    projectId: 'lingua-ai-8be27',
    authDomain: 'lingua-ai-8be27.firebaseapp.com',
    storageBucket: 'lingua-ai-8be27.firebasestorage.app',
    measurementId: 'G-FV8J82126G',
  );
}
